import { Inter, Quicksand } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';
import { UserProvider } from './context/UserContext';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${quicksand.variable} antialiased`}>
        <UserProvider>
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 3000,
              style: { background: 'transparent', boxShadow: 'none' },
            }}
          />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
